### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by swanderz**

### CODE REVIEW

**Comment by alittlesliceoftom** [comment]
Awesome work!

Can we also add instructions to run in local to the README.md?

**Comment by alittlesliceoftom** [comment]
It might help to have a consistent approach if some standard is defined.

**Comment by alittlesliceoftom** [comment]
no dbt_project.yml found at expected path /root/project/dbt-utils/dbt_project.yml

This error is actually same error i was getting when trying to run tests on local following the ci config. I assumed it was a clever CI setup thing.

**Comment by swanderz** [comment]
> Can we also add instructions to run in local to the README.md?
yeah totally. if you can tell by my commits in this PR, I'm really no expert and am just throwing things at the wall to see what sticks...

The rough sketch of it is:
1. open terminal in `integration_tests/dbt_utils`
2. configure your `~/.dbt/profiles.yml` to have an `integration_tests` section with a `sqlserver` target set as the default like `integrations_tests/ci/sample.profiles.yml` does
2. run all the commands listed in the "Run Tests - dbt-utils" step of `.circleci/config.yml` namely:
    ```bash
    dbt deps --target sqlserver
    dbt seed --target sqlserver --full-refresh
    dbt run --target sqlserver --full-refresh
    dbt test --target sqlserver
    ```

**Comment by swanderz** [comment]
> no dbt_project.yml found at expected path /root/project/dbt-utils/dbt_project.yml
> 
> This error is actually same error i was getting when trying to run tests on local following the ci config. I assumed it was a clever CI setup thing.

same! what in the name of Linus Torvalds is going on here... It has something to do with how the `integration_tests` folder is somehow missing...

image

**Comment by swanderz** [comment]
it has something to do with importing the `dbt-utils` repo as a submodule, something with which I'm very unfamiliar and will prolly have to lean on @jtcohen6  to help with...

**Comment by swanderz** [comment]
closing in favor of #5

**Pull request closed without merging**
