### PR TITLE
Manually specify varchar length to max length 

### PR DESCRIPTION
**Pull request by alittlesliceoftom**
allowed whilst still enabling indexes. Maybe  a tiny bit less performant than default (30) but much more flexible.

This is a competing PR to #14 . 

Hopefully it enables the same functionality gain with less code.

### CODE REVIEW

**Comment by alittlesliceoftom** [comment]
Surrogate key passes tests from this change. 

What do you think @swanderz

**Comment by swanderz** [comment]
@jkock what do you think?

**Comment by jkock** [comment]
From a SQL database optimization point of view, this seems to be overdoing it. But on the other hand is it also a bad optimization to need to rewrite all macro's for SQL server because of this little issue.

So, I guess this would be OK

**Comment by alittlesliceoftom** [comment]
@jkock if you notice performance issues then we could consider reducing length or reverting to the many rewrites at a later date, but agger with @swanderz merging this until those performance issues are raised as an actual issue by a user in practice. :)

**Pull request merged**
